# Generated by Django 5.2.4 on 2025-07-29 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(
                related_name="rsvp_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
