# Generated by Django 5.2.4 on 2025-07-13 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_participant_email_alter_participant_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
        migrations.AlterField(
            model_name="event",
            name="participant",
            field=models.ManyToManyField(
                related_name="rsvp_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
