# Generated by Django 5.2.4 on 2025-10-26 05:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_evn_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evn_img',
            field=cloudinary.models.CloudinaryField(default='event_img/default_img', max_length=255, verbose_name='image'),
        ),
    ]
