# Generated by Django 5.2.4 on 2025-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_evn_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evn_img',
            field=models.ImageField(blank=True, default='event_img/default_img.jpg', null=True, upload_to='event_img'),
        ),
    ]
