# Generated by Django 5.2.4 on 2025-10-26 05:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_evn_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evn_img',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dedj65xds/image/upload/v1761413435/default_img_psnmf3.jpg', max_length=255, verbose_name='image'),
        ),
    ]
